"use client"

import { useState } from "react"
import { FilterItem } from "./filter-item";

export const FilterArea = () => {
    const [selected, setSelected] = useState("Todos");

    return(
        <section className="flex flex-col gap-3 mt-[64px]">
            <div className="flex-1 flex items-center gap-[30px] mb-6 overflow-x-hidden">
                <FilterItem 
                    label="Todos"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="A"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="B"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="C"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="D"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="E"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="F"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="G"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="H"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="I"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="J"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="K"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="L"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="M"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="N"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="O"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="P"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="Q"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="R"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="S"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="T"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="U"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="V"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="W"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="X"
                    selected={selected}
                    setSelected={setSelected}            
                />
                <FilterItem 
                    label="Y"
                    selected={selected}
                    setSelected={setSelected}            
                />
            </div>
            
            <div className="w-full h-[4px] bg-[#151B26] rounded-3xl cursor-pointer">               
                <div className="w-[219px] h-[4px] bg-[#00A3FF] rounded-3xl"></div>
            </div>
        </section>
    )
}